### ISSUE TITLE
Add list area and beufify it

### ISSUE THREAD

**Issue by JouhnyKoh** [JouhnyKoh/JobsManagementApp#1]
Hi, i designed an UI in dark mode for Admin User Dashboard as follow:
 
![image](https://user-images.githubusercontent.com/115682262/195553430-c21b35d5-8f3e-427d-88a3-51adfd061bd3.png)

However, my teacher want me to change it to light mode, so I changed it a little bit:
 
![image](https://user-images.githubusercontent.com/115682262/195553453-a49b4cec-68df-40a0-9083-f13b075479fb.png)

The problem is that, i have no idea about how to styling list drop item (color) and WPF code for each item was repeated.
 
![image](https://user-images.githubusercontent.com/115682262/195553484-59bc0b18-34ce-4754-98df-d51fe82bd94f.png)

Can you help me to create the above list area and styling it?

**Comment by baokhoa-code** [comment]
Can you assign this issue to me? I think i can do it.

**Comment by JouhnyKoh** [comment]
> Can you assign this issue to me? I thin
